COMPONENT = {
    "name": "hero",
    "title": "Hero",
    "version": "1.0",
    "description": "Вводная секция страницы с текстом, действиями и необязательной медиа-зоной.",
    "template": "repui/components/hero/hero.html",
    "styles": ("repui/components/hero/hero.css",),
    "contract_styles": ("repui/theme/contract/components/hero-tokens.css",),
    "scripts": (),
    "runtime": False,
    "htmx": {"inner_html": True, "outer_html": True, "mount_required": False, "cleanup_required": False},
    "status": "experimental",
    "api": {
        "title": {"required": True},
        "image": {"default": None},
        "image_dark": {"default": None},
        "atlas": {"default": None},
        "atlas_column": {"default": 0, "choices": (0, 1, 2)},
        "image_alt": {"default": ""},
        "image_position": {"default": "center"},
        "image_dark_position": {"default": None},
        "size": {"default": "md", "choices": ("sm", "md", "lg")},
        "media_side": {"default": "end", "choices": ("start", "end")},
    },
}
