COMPONENT = {
    "name": "theme_preview",
    "title": "Theme Preview",
    "version": "1.0",
    "description": "Карточка темы с preview-зоной, описанием и действиями.",
    "template": "repui/components/theme_preview/theme_preview.html",
    "styles": ("repui/components/theme_preview/theme-preview.css",),
    "contract_styles": ("repui/theme/contract/components/theme-preview-tokens.css",),
    "scripts": (),
    "runtime": None,
    "htmx": {"inner_html": True, "outer_html": True, "mount_required": False, "cleanup_required": False},
    "api": {
        "name": {"required": True},
        "title": {"required": True},
        "description": {"default": ""},
        "image": {"default": None},
        "image_dark": {"default": None},
        "atlas": {"default": None},
        "atlas_column": {"default": 0, "choices": (0, 1, 2)},
        "image_alt": {"default": ""},
        "image_position": {"default": "center"},
        "image_dark_position": {"default": None},
        "href": {"default": None},
        "selected": {"default": False},
        "badge": {"default": None},
    },
    "status": "experimental",
}
