import {animateDisclosure} from "../core/motion.js";
export class Accordion{
  constructor(root){this.root=root;this.multiple=root.hasAttribute('data-multiple');this.items=[...root.querySelectorAll('[data-rui-accordion-item]')];this.bind();this.sync();}
  bind(){this.items.forEach((item,index)=>{const trigger=item.querySelector('[data-rui-accordion-trigger]');trigger?.addEventListener('click',()=>this.toggle(index));trigger?.addEventListener('keydown',e=>this.navigate(e,index));});}
  navigate(event,index){const triggers=this.items.map(i=>i.querySelector('[data-rui-accordion-trigger]')).filter(Boolean);let next=index;if(event.key==='ArrowDown')next=(index+1)%triggers.length;else if(event.key==='ArrowUp')next=(index-1+triggers.length)%triggers.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=triggers.length-1;else return;event.preventDefault();triggers[next]?.focus();}
  toggle(index){const item=this.items[index];const trigger=item.querySelector('[data-rui-accordion-trigger]');const opening=trigger.getAttribute('aria-expanded')!=='true';if(opening&&!this.multiple)this.items.forEach((_,i)=>i!==index&&this.set(i,false));this.set(index,opening);this.root.dispatchEvent(new CustomEvent('rui:accordionchange',{bubbles:true,detail:{index,open:opening}}));}
  set(index,open){const item=this.items[index];const trigger=item.querySelector('[data-rui-accordion-trigger]');const panel=item.querySelector('[data-rui-accordion-panel]');trigger?.setAttribute('aria-expanded',String(open));item.dataset.state=open?'open':'closed';if(panel)animateDisclosure(panel,open);}
  sync(){this.items.forEach(item=>{const trigger=item.querySelector('[data-rui-accordion-trigger]');const panel=item.querySelector('[data-rui-accordion-panel]');const open=trigger?.getAttribute('aria-expanded')==='true';item.dataset.state=open?'open':'closed';if(panel)panel.hidden=!open;});}
}
export function initAccordions(root=document){return[...root.querySelectorAll('[data-rui-accordion]')].map(el=>el.__ruiAccordion||(el.__ruiAccordion=new Accordion(el)));}
